<?php declare(strict_types=1);

namespace App\Filament\Resources\ProductResource\Pages;

use App\Filament\Resources\ProductResource;
use App\Models\Chat;
use Filament\Resources\Pages\CreateRecord;

class CreateProduct extends CreateRecord
{
    protected static string $resource = ProductResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->user()->id;
        $data['model_type'] = Chat::class;

        unset($data['duration_time_seconds']);

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
