<?php

namespace App\Filament\Resources\TelegramVideoResource\Pages;

use App\Filament\Resources\TelegramVideoResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateTelegramVideo extends CreateRecord
{
    protected static string $resource = TelegramVideoResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        dd($data);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

}
