<?php declare(strict_types=1);

namespace App\Filament\Resources\ChatResource\Actions;

use App\Repositories\BotChatRepository;
use App\Services\Messengers\Telegram\ChatTelegramManager;
use Closure;
use Filament\Actions\Concerns\CanCustomizeProcess;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Notifications\Notification;
use Filament\Support\Enums\IconPosition;
use Filament\Tables\Actions\Action;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\HtmlString;

class RemoveMemberAction extends Action
{

    use CanCustomizeProcess;

    protected string|Htmlable|Closure|null $label = 'Expulsar Membro';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this
            ->modal()
            ->form([
                MarkdownEditor::make('description')
                    ->toolbarButtons([
                        'bold',          // <b>bold</b>, <strong>bold</strong>, **bold**
                        'italic',        // <i>italic</i>, <em>italic</em>, *italic*
                        'codeBlock',     // <code>code</code>, `code`
                        'strike',        // <s>strike</s>, <strike>strike</strike>, <del>strike</del>, ~~strike~~
                        'underline',     // <u>underline</u>
                    ])
                    ->label(new HtmlString(__('Você pode enviar um texto customizado (<strong style="color: #1e40af">opcional</strong>)')))
                    ->nullable()
            ]);

        $this->button()
            ->color('danger')
            ->iconPosition(IconPosition::Before)
            ->icon('heroicon-o-trash')
            ->hidden(fn($record) => $record->is_expired)
            ->action(function (): void {
                $this->process(function (array $data, Model $record) {

                    $result = BotChatRepository::make()
                        ->getChatAndBot((int)$record->chat_id);

                    $chatTelegramManager = ChatTelegramManager::make()
                        ->setBot($result['bot'])
                        ->setChat($result['chat']);

                    $notification = Notification::make();

                    $chatMember = $chatTelegramManager->getChatMember(
                        $record->member->code,
                        false
                    );

                    if (!$chatMember) {
                        $record->expired_at = now()->subSecond();
                        $record->already_kicked = 1;
                        $record->save();

                        $notification
                            ->info()
                            ->body(__('Esse membro não está mais no grupo, mas foi banido do sistema da mesma forma por garantia'))
                            ->send();
                        return;
                    }

                    if ($chatMember->status === 'creator') {
                        $notification
                            ->info()
                            ->body(__('Esse membro é o dono do grupo e não pode ser expulso'))
                            ->send();
                        return;
                    }

                    $result = $chatTelegramManager->removeMember([
                        'user_id' => $record->member->code,
                        'text' => $data['description'] ?? null
                    ]);

                    if (!$result) {
                        $notification->danger()
                            ->body(__('Não foi possível expulsar o membro do grupo'));
                    } else {

                        $record->expired_at = now()->subSecond();
                        $record->save();

                        $notification->success()
                            ->body(__('Membro expulso do grupo com sucesso'));
                    }

                    $notification->send();
                });
            });
    }

    public function getName(): ?string
    {
        return 'remove_member';
    }

}
